<section>
	<div class="contents">
		<div class="hgroup1">
			<h1>マイページ</h1>
		</div>
		<?php 
			$id   = $this->model('Login')->GetLoginID();
			$flag = $this->pdo()->quick(" shop_flag <- t_customer.account_id = $id ");
		?>
		<?php if ($flag == 1):?>
		<p><a href="<?=$this->ConvertURL('/myshop')?>">マイショップ</a></p>
		<?php endif ?>
		<p><a href="<?=$this->ConvertURL('/mypage/mycoupon')?>">マイクーポン</a></p>
		<p><a href="<?=$this->ConvertURL('/mypage/customer')?>">登録情報</a></p>
		<p><a href="<?=$this->ConvertURL('/logout')?>">ログアウト</a></p>
	</div>
</section>
